### ISSUE TITLE
D&D on IB not working

### ISSUE THREAD

**Issue by gitric** [appdevdesigns/appdev-opsportal#107]
the drag and drop ordering of page components in the Interface builder does not work anymore. I can drag and drop a grid over a menu and they just revert back to their old positions. @wongpratan

**Comment by appdevdesigns** [comment]
UPDATE: I can now D&d a component in the list and it stays there at first. After editing and saving one of the components though, it the component list reverts or goes back to the original position.

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/7f4db8440c59a13a3ec3c20c50feecb951713965
