### ISSUE TITLE
AB Objects are changing after sync

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#111]
column names are displaying in a different order after sync. Also, connection fields are not showing column name

<img width="1192" alt="screen shot 2016-10-30 at 3 08 08 pm" src="https://cloud.githubusercontent.com/assets/3607052/19835265/0b6c22cc-9eb3-11e6-9f76-4d1b757cad5c.png">

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/f47986a09d31bdbd54b60e0302e22e9487ff4f90
