### ISSUE TITLE
Single Line Text Field Type ignored status of [support multilingual]

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#112]
Single Line Text Field Type ignored status of [support multilingual] and created the field as multilingual anyway.

Then after Synchronizing the Object, the resulting display lost all my entered data.

**Comment by appdevdesigns** [comment]
#116

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/3015314b445555f1841a70ea8b0d2270867747ed
