### ISSUE TITLE
Edit object needs menu back to parent

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#115]
When the quick page adds an edit page it does not add a menu to go back to parent page.

**Comment by wongpratan** [comment]
Add Link component - https://github.com/appdevdesigns/app_builder/commit/ae0aa3e1cb70c06884d2c462f35d4cb4f151e189

Add Link back to Quick Page - 
https://github.com/appdevdesigns/app_builder/commit/65918a6e7e271f3ca370f6844f468d89b7ffeac8
