### ISSUE TITLE
title on single column grid will wrap if longer than one word

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#117]
![screen shot 2016-11-02 at 11 11 01 am](https://cloud.githubusercontent.com/assets/3607052/19916514/27b9cd4e-a0ed-11e6-9da1-8dc57e26fe19.png)

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/c1776b9896b7937a11dcc30de31de0f40882a55d
