### ISSUE TITLE
grid on generated UI not showing multiple connected fields

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#118]
seems to be only happening with one record

**Comment by wongpratan** [comment]
Fixed
https://github.com/appdevdesigns/app_builder/commit/a4570ecc0a0980bb2a5773c9fb7ebe0f09b60ed8
https://github.com/appdevdesigns/app_builder/commit/4aa9bdba1030f01b64e1572e010d555e993898b1
