### ISSUE TITLE
edit the record from a view details page and the page loses connection with record

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#119]
( pages created by Quick add) example: view detials of a Owner and then edit the Owener. After saving, it returns to the detials page but the owner is missing from the page. 

https://www.dropbox.com/s/rzaipcu9c3w5ez0/Kapture%202016-11-02%20at%2012.30.48.mp4?dl=0

**Comment by wongpratan** [comment]
Fixed
