### ISSUE TITLE
add a new record from a view detials does not update grid after saving 

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#120]
Quick add pages: go to view detials of Owner, add new Pet, save and return to view Owners. 
The owner record is updated to show new pet but the Pet grid on the page is not. 

https://www.dropbox.com/s/a56p6gnoreikw6a/Kapture%202016-11-02%20at%2012.54.53.mp4?dl=0

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/1e44bf8846cfade71e351c578b1e5c5d0dd3a724
