### ISSUE TITLE
Data Field  .type field is incorrectly being used in the Webix Display.

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#122]
The Webix Grid/Form is using the dataField.type value in it's display of the data.  

The .type field should only effect the server side SailsJS data type for the field.  Not the Webix display, editor type.

**Comment by wongpratan** [comment]
https://github.com/appdevdesigns/app_builder/commit/a4570ecc0a0980bb2a5773c9fb7ebe0f09b60ed8
