### ISSUE TITLE
Cleared linked cell not clearing after save.

### ISSUE THREAD

**Issue by KenWade** [appdevdesigns/appdev-opsportal#129]
Steps to reproduce:  edit the 4th row (BD). Clear the contents of the "Requests" Cell. Press Save - which returns to the table. Requests cell not cleared.

![image](https://cloud.githubusercontent.com/assets/14247188/20034569/c85d0838-a3f4-11e6-825b-cfc921f325d2.png)

![image](https://cloud.githubusercontent.com/assets/14247188/20034573/f9a46440-a3f4-11e6-95d6-06e827c05744.png)

**Comment by KenWade** [comment]
Clarification: the bottom value ("Requests") in the Edit ContactList (the top jpg) is cleared and saved.  Then returning to the ContactList view the value of "Requests" still contains a value rather than "No data selected".

**Comment by wongpratan** [comment]
Fixed
