### ISSUE TITLE
New Feature - Need cancel option.

### ISSUE THREAD

**Issue by KenWade** [appdevdesigns/appdev-opsportal#131]
On the live application I edited a row, then selected a linked cell.  The popup comes up successfully.
However, there is no cancel option to simply do nothing.  This could be important if the user accidentally changes the selection and can't get back to the original setting of the cell. 

![image](https://cloud.githubusercontent.com/assets/14247188/20035192/a388cc96-a40c-11e6-9cfa-c730d4b03f4e.png)

**Comment by wongpratan** [comment]
Implemented - https://github.com/appdevdesigns/app_builder/commit/fd2911ace1aaa2c19e7cfb58d15361ec86678294
