### ISSUE TITLE
Theme Builder: refactor to use more standard RESTful routes

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#134]
Use this site for a good example:

http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by jamesduncan** [comment]
Ready for review...there is one portion where I was working on getting it to look at little better so that can be removed if you would like the commit to be only related to the routes.

**Comment by thaicrc** [comment]
Hi James…. why am I receiving this?

Bruce

**Comment by jamesduncan** [comment]
I was going back and cleaning up old Github issues and I think you name was added with mine way back in the 2016 Hackathon. Sorry to spam you!
