### ISSUE TITLE
remove null description in app list

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#156]
when a person does not enter a description for an app in the app builder, it should just be blank on the app list instead of saying null

![screen shot 2016-11-14 at 3 47 43 pm](https://cloud.githubusercontent.com/assets/3607052/20258428/30ad2b6e-aa82-11e6-8281-b5dfc0dba3bb.png)

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/663dd97c5aec44b8f14e0c65c62b93f7f7c29931
