### ISSUE TITLE
when adding a new column, go straight to short text field

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#157]
this is what happens now when clicking new column. 

![screen shot 2016-11-14 at 3 56 13 pm](https://cloud.githubusercontent.com/assets/3607052/20258716/862ee2e8-aa83-11e6-8715-c05a66fc56b3.png)

Instead, go straight to this popup. 

![screen shot 2016-11-14 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/3607052/20258724/8ece9b46-aa83-11e6-8557-8fe2152830b4.png)

**Comment by wongpratan** [comment]
https://github.com/appdevdesigns/app_builder/commit/f225ea2c198fc979f1ba42edbfcec90ebdfa3bc2
