### ISSUE TITLE
Label field should go first

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#158]
On adding a column/field, the Label should go first and the field name built from the Label. 

Maybe field Name should be disabled? The user really only needs to create a Label. The system can create the Name

![screen shot 2016-11-14 at 4 09 17 pm](https://cloud.githubusercontent.com/assets/3607052/20258982/f705c3dc-aa84-11e6-9608-e85f7ab190cf.png)

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/a7d9eec46947c684580c1e2e9cbe449d118aae11
