### ISSUE TITLE
number field not working on forms

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#162]
does not work on add or edit forms

<img width="655" alt="screen shot 2016-11-24 at 10 05 53 pm" src="https://cloud.githubusercontent.com/assets/3607052/20603205/0c028ae8-b293-11e6-9db4-b253bf722193.png">

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/561a569cdcd46e7ead9552aca86ab4fc1319ed20
