### ISSUE TITLE
2 columns goes off screen on pop-up

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#164]
<img width="694" alt="screen shot 2016-11-24 at 10 39 26 pm" src="https://cloud.githubusercontent.com/assets/3607052/20604036/f9341dba-b296-11e6-9550-afcf127e6949.png">

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/38ad7fa0d69b4f7c3209c4a1fe83245c3e63e8f1
