### ISSUE TITLE
editing a child record sometimes gives wrong parent

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#170]
For instance: I have a grid with Owners and a grid with Pets. I edit a Owner from the grid and then I edit a Pet with a different Owner. However, the edit page shows the previously selected Owner instead of the actual Owner. 

In this pic you can see one Owner is selected and a Pet with a different Owner is also selected. The edit page shows the wrong Owner. 

![screen shot 2016-12-08 at 10 04 41 am](https://cloud.githubusercontent.com/assets/3607052/20996213/8e26c160-bd2e-11e6-8732-5d4bdc8a4895.png)

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/6ddb107da4471acb30a820c8e2d1ac2df92c379d
