### ISSUE TITLE
AppBuilder: Interface Editor : Grid Editor : initial column selections are out of sync

### ISSUE THREAD

**Issue by Hiro-Nakamura** [appdevdesigns/appdev-opsportal#187]
On a Page in the Interface Builder:

add a Grid
[edit] the grid
select an object

The object's initial list of columns appear, and all columns are checked by default.

[uncheck] a column
nothing happens

[check] the column
only that column shows up in the display (the remaining columns are still checked)

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/c2e47a47691c0c590580a89fd70bd404edf005a3
