### ISSUE TITLE
Group Add feature

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#188]
Add a feature that allows add multiple new records to an object based on a selected group from a linked object. 
example: 
Children each have a Visit log. A group of children go on an outing to the same place. A user can go to a page to select the group of children and then key in data to a form that will insert new records into the visit object based on the group of selected children. 

![screen shot 2017-01-18 at 3 45 53 pm](https://cloud.githubusercontent.com/assets/3607052/22057216/52f2fac2-dd96-11e6-9fae-9547e541ecd8.png)
What it could look like to do a group add

![screen shot 2017-01-18 at 3 45 25 pm](https://cloud.githubusercontent.com/assets/3607052/22093469/784e4d56-de38-11e6-8f1c-9a103e3790fc.png)
Modify the Mass Update to make the grid selectable independent of Mass Update so other forms can use the selection for adding/updating linked objects. 

![screen shot 2017-01-19 at 11 05 27 am](https://cloud.githubusercontent.com/assets/3607052/22093479/8856e1ea-de38-11e6-8f5f-d12d35423e64.png)
modify the Form options to allow a linked object and a choice to Add or Update when a Group is selected.

**Comment by appdevdesigns** [comment]
Do the Add option first and let us test it out. Then you can work on the Update option.

**Comment by wongpratan** [comment]
Implemented
https://github.com/appdevdesigns/app_builder/commit/1b90f67d23674ad16ff33c2e2c2decde25b9256f
https://github.com/appdevdesigns/app_builder/commit/9448c50a0f4ceb55685a9d04c5ae1188b56da576
https://github.com/appdevdesigns/app_builder/commit/6320d1081243226f9a82d29b7ed84dbac19009db
