### ISSUE TITLE
When click link "Add new colume" Objects app_builder page panel to not fit into container.

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#189]
Steps
1.  Go to App builder page.
2. Click "Objcets" Menu 
3. click "+ Add new column" and click "Choose field type.."
4. select "Date" or "Number"  

Actual result:
- panel to not fit into container. (see image)

Expected result:
- panel to fit into contailner.

![image](https://cloud.githubusercontent.com/assets/22674758/22503334/d3d87c6c-e8a3-11e6-9fc4-0a1589654cf2.png)

**Comment by appdevdesigns** [comment]
@kidlovess Fixed

**Comment by wongpratan** [comment]
@kidlovess Fixed

**Comment by kidlovess** [comment]
Test passed.
@wongpratan
