### ISSUE TITLE
Setting not clear or reset value when add net column completed.

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#191]
steps :
1. Go to app builder page.
2. Click "+ add new column" button
3.  select field type and complete setting value 
5. click Add column
6. Try again add column follow step 2 - 5.

Actual Result:
- old setting not clear or reset.

Expected result:
- setting should be reset and clear value.

![image](https://cloud.githubusercontent.com/assets/22674758/22536392/0c1bb748-e934-11e6-82ed-732763a0a43a.png)

**Comment by appdevdesigns** [comment]
@kidlovess Fixed

**Comment by wongpratan** [comment]
@kidlovess Fixed

**Comment by kidlovess** [comment]
Test passed.
@wongpratan
