### ISSUE TITLE
Field type can't save when fill a long text input.

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#199]
Text branch : develop

steps:
1. Go to App builder page.
2. select field type and fill **_long_** text to input text.
3. click add row

Actual result:
- can't save field type.

Expected result:
- should be save field type.

![image](https://cloud.githubusercontent.com/assets/22674758/22728411/5fb76542-ee10-11e6-8d52-d97cec966323.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728418/6589a78c-ee10-11e6-94f1-adea02d2a5d9.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728421/67f94e96-ee10-11e6-9554-011718b2419f.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728425/6d29292c-ee10-11e6-9c2b-8541a6dec99f.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728430/72126cbe-ee10-11e6-9a04-c38dcc7b87d1.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728431/767dc80c-ee10-11e6-9d16-0e3a6d952a82.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728433/7b921e4c-ee10-11e6-8ae3-806e63e9149c.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728434/80670ca2-ee10-11e6-94d5-4e7d826f84d2.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728441/856d2c5e-ee10-11e6-989e-418a30ebd455.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728442/8a1ccf48-ee10-11e6-9111-b4737ba0d6f4.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22728445/8f597ac4-ee10-11e6-93f5-c8e19629ab96.png)

**Comment by wongpratan** [comment]
Fixed @kidlovess

**Comment by kidlovess** [comment]
Test passed.
@wongpratan
