### ISSUE TITLE
label name not auto running number.

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#201]
Test branch : develop

Steps:
1. Go to app builder page.
2. Create "Add new object" 
3. Create "Single line text" field type 
4. Create field type step 4 again.

Acutal Result:
- label name not auto running number.

Expected Result:
- label name not duplicate

![image](https://cloud.githubusercontent.com/assets/22674758/22791193/1a8b256a-ef1b-11e6-9a04-f0bfe0398be1.png)

**Comment by wongpratan** [comment]
It's fixed.
@kidlovess

**Comment by kidlovess** [comment]
Test passed.
@wongpratan
