### ISSUE TITLE
no have scrollbar when edit properties of component interface tab 

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#204]
Test branch : develop

Steps:
1. Go to app builder and click interface tab
2. drag/drop component to page layout.
3. click edit 

Actual Result:
- no have scrollbar

Expected Result:
- should have scrollbar

![image](https://cloud.githubusercontent.com/assets/22674758/22888510/92d9adb4-f238-11e6-845e-a4a8c11be118.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22888515/97a7fe40-f238-11e6-90f3-0b3404aa3403.png)

**Comment by wongpratan** [comment]
It's fixed.
@kidlovess

**Comment by kidlovess** [comment]
Test passed.
@wongpratan
