### ISSUE TITLE
when text label is blank , page layout in interface tab label invalid 

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#209]
Test branch : develop

Steps:
1. Go to app builder 
2. add new column and insert blank text (space bar)
3. Go to interface tab and create form in page layout.

Actual Result:
- page layout in interface tab label invalid 

Expected Result:
-  label should be valid.

![image](https://cloud.githubusercontent.com/assets/22674758/22958564/b1ce0e10-f362-11e6-8466-945355f1354e.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22958568/b4a49532-f362-11e6-83bc-20caceadd9b9.png)

![image](https://cloud.githubusercontent.com/assets/22674758/22958573/b859206c-f362-11e6-9c84-8d3d412fb576.png)

**Comment by wongpratan** [comment]
Fixed
@kidlovess

**Comment by kidlovess** [comment]
test pass
@wongpratan
