### ISSUE TITLE
Application can't delete

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#212]
Test branch: Develop

Steps:
1. Go to app builder 
2. Create new application
3. Click "gear" icon and click "bin" icon Deleted

Actual Result:
- Application can't delete

Expected Result:
- Application can delete

![image](https://cloud.githubusercontent.com/assets/22674758/23062617/085a590a-f539-11e6-8dad-e2c5e75d5467.png)

![image](https://cloud.githubusercontent.com/assets/22674758/23062617/085a590a-f539-11e6-8dad-e2c5e75d5467.png)

**Comment by wongpratan** [comment]
It's fixed
@kidlovess

**Comment by kidlovess** [comment]
Test pass.

@wongpratan
