### ISSUE TITLE
Go to should not select the own page

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#213]
Test branch: develop

Steps:
1. Go to app builder page and select interface menu.
2. select link view and link properties "Go to" 

Actual Result:
- go to menu can select the own page.

Expected Result:
- go to menu should not select the own page.

![image](https://cloud.githubusercontent.com/assets/22674758/23063758/b8843562-f53e-11e6-91a0-763c808d4110.png)

**Comment by wongpratan** [comment]
It's fixed
@kidlovess

**Comment by kidlovess** [comment]
Test passed.

@wongpratan
