### ISSUE TITLE
Tab name , choose an icon not working 

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#215]
Test Branch : develop

Steps:

1. Go to app builder and select interface tab
2. select page and select Tab in components.
3. Click edit and click "Choose an icon"

Actual Result:
- Choose an icon not working 

Expected Result:
- choose an icon should working

![image](https://cloud.githubusercontent.com/assets/22674758/23119056/3207f008-f789-11e6-8b56-958af9c9997a.png)

**Comment by wongpratan** [comment]
Fixed
@kidlovess

**Comment by kidlovess** [comment]
Test passed.

@wongpratan  @appdevdesigns
