### ISSUE TITLE
when user click Hide all , the column show bin icon (not hidden)

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#219]
Test branch :develop

Steps:
1. Go to app builder
2. click object page and click menu "Hide fields"
3. Click select "Hide all"

Actual Result:
- the column show bin icon

Expected Result:
- the column should not show bin icon

![image](https://cloud.githubusercontent.com/assets/22674758/23202778/38ce224c-f912-11e6-904e-b1496eada8f3.png)

**Comment by wongpratan** [comment]
Fixed @kidlovess

**Comment by kidlovess** [comment]
Test passed
@wongpratan  @appdevdesigns
