### ISSUE TITLE
when user select name and salary , "field 3" should not select   

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#220]
Test branch : develop

Steps:
1. Go to app builder.
2. Click Object and Click Frozen columns
3. Click Name , Salary (see images)

Actual Result:
-  "field 3" selected by user not select  

Expected Result:
- "field 3" should not select  

![image](https://cloud.githubusercontent.com/assets/22674758/23203329/a4b0295e-f914-11e6-8cd6-d96c6e373f11.png)

**Comment by wongpratan** [comment]
It should be fixed.
https://github.com/appdevdesigns/app_builder/commit/bedb8aa69015bb6bd2aef8a98dfe1f4ddd9c1eb1

@kidlovess

**Comment by kidlovess** [comment]
Test passed

@wongpratan  @appdevdesigns
