### ISSUE TITLE
when user delete object , the old page not refresh

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#221]
Test branch : develop

Steps:
1. Go to app builder.
2. Go to Object page and delete object (see image)
3. delete new object

Actual Result:
- old page not refresh or clear.

Expected Result:
- old page should clear page or refresh.

![image](https://cloud.githubusercontent.com/assets/22674758/23210446/2d150af6-f930-11e6-9143-8ade4be25703.png)

![image](https://cloud.githubusercontent.com/assets/22674758/23210453/3079376c-f930-11e6-8167-5251b447135a.png)

**Comment by wongpratan** [comment]
It should be fixed - https://github.com/appdevdesigns/app_builder/commit/590587be8f4c17cd8a17ac3546434ba1dc741176

@kidlovess

**Comment by kidlovess** [comment]
Test passed.

@wongpratan @appdevdesigns
