### ISSUE TITLE
row not edit in object page

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#223]
Test branch: develop

Steps:
1. Go to app builder and go to objects page.
2. create follow images.
3. click object "test"
4. click object "test3"
5. click object "test" and click row in Field 1 and click row in Filed 2 

Actual Result:
- row not edit

Expected Result:
- row should edit.

![image](https://cloud.githubusercontent.com/assets/22674758/23250390/88576598-f9db-11e6-9315-1973942a7c53.png)

![image](https://cloud.githubusercontent.com/assets/22674758/23250406/9e5c0362-f9db-11e6-951f-e024bd1efde4.png)

**Comment by wongpratan** [comment]
It's fixed.
https://github.com/appdevdesigns/app_builder/commit/439ef9f52949c31bb388ee1d1001501bd3398d4c

@kidlovess

**Comment by kidlovess** [comment]
Test passed.
@wongpratan @appdevdesigns
