### ISSUE TITLE
add new object use old name , bin icon should not show

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#224]
Test branch : develop

Steps:
1. Go to App builder.
2. Go to Objects page.
3. Add new object and delete object.
4. Add new object again and user old name.

Actual Result:
- add new object use old name , bin icon should show

Expected Result:
- add new object use old name , bin icon should show

![image](https://cloud.githubusercontent.com/assets/22674758/23253403/f6b966a2-f9e6-11e6-96a3-3b6137f80f43.png)

**Comment by wongpratan** [comment]
Fixed
@kidlovess

**Comment by kidlovess** [comment]
Test passed @wongpratan  @appdevdesigns
