### ISSUE TITLE
when user click "delete" and  add new object again,  the list new object not show

### ISSUE THREAD

**Issue by kidlovess** [appdevdesigns/appdev-opsportal#226]
Test branch: develop

Steps:
1. Go to app builder.
2. Add new object.
3. Delete "object" follow 2.
4. add new object again.

Actual Result:
- user click "delete" and  add new object again,  the list new object not show

Expected Result:
- new object should show

![image](https://cloud.githubusercontent.com/assets/22674758/23603916/8e13cbaa-0289-11e7-8f22-5893995f94d6.png)

![image](https://cloud.githubusercontent.com/assets/22674758/23604127/59b2a6dc-028a-11e7-9421-a6b8a795228f.png)

**Comment by wongpratan** [comment]
Fixed
https://github.com/appdevdesigns/app_builder/commit/6a691cb8cb4a242807f4a8c2973fc13f9c79161e

**Comment by kidlovess** [comment]
Test passed.

@wongpratan @appdevdesigns
