### ISSUE TITLE
CSV Import causing error 

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#243]
When importing this file, there is a bug indicated regarding type (date type I guess). However, it still creates the object but sometimes with missing fields. Unfortunately, there does not seem to be a corresponding data table because no data can be saved from the object. 

my test data

"School","Start Date","Leave Date","Child"
"Cool","04/03/2017","","JumeJume Marlene"
"school 1","05/11/2007","03/20/2014","Sansean Yoraphat"
"Cool","05/12/2014","","Sansean Yoraphat"
"school 1","11/02/2016","10/26/2017","Ursula Kyla Allen"
"school 1","02/01/2013","08/31/2014","Ursula Kyla Allen"
"Hang Dong","09/01/2014","11/02/2016","Ursula Kyla Allen"
"school 1","10/14/2012","10/14/2016","Cheryl Aurora Acevedo"

**Comment by wongpratan** [comment]
Fixed
