### ISSUE TITLE
Validate model's column name

### ISSUE THREAD

**Issue by wongpratan** [appdevdesigns/appdev-opsportal#72]
At the moment, There are errors when enter special characters to column name such as " Field 1.2 "

**Comment by appdevdesigns** [comment]
Pong, 

Please validate the field name to only allow valid characters. 
ric

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/09a16af03ca123fe1ddcfddc5098d5e1ada963aa
